// Verification scaffolds for axil_regblock, generated by SemiCraft (P4-09).
//
// Simulation only: these modules drive nothing and are attached with
// SystemVerilog `bind`, so adding this file to a compile changes no
// synthesised logic and needs no edit to the design or the testbench.
// Compile it alongside axil_regblock.sv and the checks attach themselves.

module axil_regblock_wr_monitor (
    input logic aclk,
    input logic bvalid,
    input logic [1:0] bresp
);

    // Passive monitor: samples the bundle on posedge aclk when bvalid
    always @(posedge aclk) begin
        if (bvalid) begin
            $display("[%0t] axil_regblock_wr_monitor: bvalid=%0d bresp=%0d", $time, bvalid, bresp);
        end
    end

endmodule

module axil_regblock_rd_monitor (
    input logic aclk,
    input logic rvalid,
    input logic [31:0] rdata,
    input logic [1:0] rresp
);

    // Passive monitor: samples the bundle on posedge aclk when rvalid
    always @(posedge aclk) begin
        if (rvalid) begin
            $display("[%0t] axil_regblock_rd_monitor: rvalid=%0d rdata=%0d rresp=%0d", $time, rvalid, rdata, rresp);
        end
    end

endmodule

module axil_regblock_axil_checker (
    input logic aclk,
    input logic areset_n,
    input logic awvalid,
    input logic bvalid,
    input logic arvalid,
    input logic rvalid,
    input logic [31:0] rdata,
    input logic [1:0] rresp
);

    // write_response_arrives: bvalid must arrive within 16 cycles of awvalid
    logic write_response_arrives_pending;
    logic [31:0] write_response_arrives_wait;
    always @(posedge aclk) begin
        if (!areset_n) begin
            write_response_arrives_pending <= 1'b0;
            write_response_arrives_wait <= 32'd0;
        end else if (write_response_arrives_pending) begin
            if (bvalid) begin
                write_response_arrives_pending <= 1'b0;
            end else if (write_response_arrives_wait >= 32'd16) begin
                $error("CHECK FAIL: write_response_arrives: bvalid did not arrive within 16 cycles of awvalid");
                write_response_arrives_pending <= 1'b0;
            end else begin
                write_response_arrives_wait <= write_response_arrives_wait + 32'd1;
            end
        end else if (awvalid) begin
            write_response_arrives_pending <= 1'b1;
            write_response_arrives_wait <= 32'd0;
        end
    end

    // read_data_arrives: rvalid must arrive within 16 cycles of arvalid
    logic read_data_arrives_pending;
    logic [31:0] read_data_arrives_wait;
    always @(posedge aclk) begin
        if (!areset_n) begin
            read_data_arrives_pending <= 1'b0;
            read_data_arrives_wait <= 32'd0;
        end else if (read_data_arrives_pending) begin
            if (rvalid) begin
                read_data_arrives_pending <= 1'b0;
            end else if (read_data_arrives_wait >= 32'd16) begin
                $error("CHECK FAIL: read_data_arrives: rvalid did not arrive within 16 cycles of arvalid");
                read_data_arrives_pending <= 1'b0;
            end else begin
                read_data_arrives_wait <= read_data_arrives_wait + 32'd1;
            end
        end else if (arvalid) begin
            read_data_arrives_pending <= 1'b1;
            read_data_arrives_wait <= 32'd0;
        end
    end

    // rdata_holds_between_reads: rdata stable one cycle after arvalid deasserts
    logic rdata_holds_between_reads_enable_prev;
    logic [31:0] rdata_holds_between_reads_signal_prev;
    always @(posedge aclk) begin
        rdata_holds_between_reads_enable_prev <= arvalid;
        rdata_holds_between_reads_signal_prev <= rdata;
    end
    always @(posedge aclk) begin
        if (areset_n && !rdata_holds_between_reads_enable_prev && (rdata !== rdata_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: rdata_holds_between_reads: rdata changed while arvalid was deasserted last cycle (was %0d, now %0d)", rdata_holds_between_reads_signal_prev, rdata);
        end
    end

    // rresp_holds_between_reads: rresp stable one cycle after arvalid deasserts
    logic rresp_holds_between_reads_enable_prev;
    logic [1:0] rresp_holds_between_reads_signal_prev;
    always @(posedge aclk) begin
        rresp_holds_between_reads_enable_prev <= arvalid;
        rresp_holds_between_reads_signal_prev <= rresp;
    end
    always @(posedge aclk) begin
        if (areset_n && !rresp_holds_between_reads_enable_prev && (rresp !== rresp_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: rresp_holds_between_reads: rresp changed while arvalid was deasserted last cycle (was %0d, now %0d)", rresp_holds_between_reads_signal_prev, rresp);
        end
    end

endmodule

// Attach the scaffolds. `bind` connects to nets resolved in the DUT's
// own scope, which is why every port above is named after one.
bind axil_regblock axil_regblock_wr_monitor u_axil_regblock_wr_monitor (
    .aclk(aclk),
    .bvalid(bvalid),
    .bresp(bresp)
);

bind axil_regblock axil_regblock_rd_monitor u_axil_regblock_rd_monitor (
    .aclk(aclk),
    .rvalid(rvalid),
    .rdata(rdata),
    .rresp(rresp)
);

bind axil_regblock axil_regblock_axil_checker u_axil_regblock_axil_checker (
    .aclk(aclk),
    .areset_n(areset_n),
    .awvalid(awvalid),
    .bvalid(bvalid),
    .arvalid(arvalid),
    .rvalid(rvalid),
    .rdata(rdata),
    .rresp(rresp)
);
