// Verification scaffolds for sync_ram, generated by SemiCraft (P4-09).
//
// Simulation only: these modules drive nothing and are attached with
// SystemVerilog `bind`, so adding this file to a compile changes no
// synthesised logic and needs no edit to the design or the testbench.
// Compile it alongside sync_ram.sv and the checks attach themselves.

module sync_ram_rd_monitor (
    input logic clk,
    input logic re,
    input logic [7:0] dout
);

    // Passive monitor: samples the bundle on posedge clk when re
    always @(posedge clk) begin
        if (re) begin
            $display("[%0t] sync_ram_rd_monitor: re=%0d dout=%0d", $time, re, dout);
        end
    end

endmodule

module sync_ram_rd_checker (
    input logic clk,
    input logic re,
    input logic [7:0] dout
);

    // read_data_holds_between_reads: dout stable one cycle after re deasserts
    logic read_data_holds_between_reads_enable_prev;
    logic [7:0] read_data_holds_between_reads_signal_prev;
    always @(posedge clk) begin
        read_data_holds_between_reads_enable_prev <= re;
        read_data_holds_between_reads_signal_prev <= dout;
    end
    always @(posedge clk) begin
        if (!read_data_holds_between_reads_enable_prev && (dout !== read_data_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: read_data_holds_between_reads: dout changed while re was deasserted last cycle (was %0d, now %0d)", read_data_holds_between_reads_signal_prev, dout);
        end
    end

endmodule

// Attach the scaffolds. `bind` connects to nets resolved in the DUT's
// own scope, which is why every port above is named after one.
bind sync_ram sync_ram_rd_monitor u_sync_ram_rd_monitor (
    .clk(clk),
    .re(re),
    .dout(dout)
);

bind sync_ram sync_ram_rd_checker u_sync_ram_rd_checker (
    .clk(clk),
    .re(re),
    .dout(dout)
);
