// Verification scaffolds for sync_ram, generated by SemiCraft (P4-09).
//
// Simulation only: these modules drive nothing and are attached with
// SystemVerilog `bind`, so adding this file to a compile changes no
// synthesised logic and needs no edit to the design or the testbench.
// Compile it alongside sync_ram.sv and the checks attach themselves.

module sync_ram_rd_monitor (
    input logic p_clk,
    input logic p_re,
    input logic [7:0] p_dout
);

    // Passive monitor: samples the bundle on posedge p_clk when p_re
    always @(posedge p_clk) begin
        if (p_re) begin
            $display("[%0t] sync_ram_rd_monitor: p_re=%0d p_dout=%0d", $time, p_re, p_dout);
        end
    end

endmodule

module sync_ram_rd_checker (
    input logic p_clk,
    input logic p_re,
    input logic [7:0] p_dout
);

    // read_data_holds_between_reads: p_dout stable one cycle after p_re deasserts
    logic read_data_holds_between_reads_enable_prev;
    logic [7:0] read_data_holds_between_reads_signal_prev;
    always @(posedge p_clk) begin
        read_data_holds_between_reads_enable_prev <= p_re;
        read_data_holds_between_reads_signal_prev <= p_dout;
    end
    always @(posedge p_clk) begin
        if (!read_data_holds_between_reads_enable_prev && (p_dout !== read_data_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: read_data_holds_between_reads: p_dout changed while p_re was deasserted last cycle (was %0d, now %0d)", read_data_holds_between_reads_signal_prev, p_dout);
        end
    end

endmodule

// Attach the scaffolds. `bind` connects to nets resolved in the DUT's
// own scope, which is why every port above is named after one.
bind sync_ram sync_ram_rd_monitor u_sync_ram_rd_monitor (
    .p_clk(p_clk),
    .p_re(p_re),
    .p_dout(p_dout)
);

bind sync_ram sync_ram_rd_checker u_sync_ram_rd_checker (
    .p_clk(p_clk),
    .p_re(p_re),
    .p_dout(p_dout)
);
