// Verification scaffolds for axil_intc, generated by SemiCraft (P4-09).
//
// Simulation only: these modules drive nothing and are attached with
// SystemVerilog `bind`, so adding this file to a compile changes no
// synthesised logic and needs no edit to the design or the testbench.
// Compile it alongside axil_intc.sv and the checks attach themselves.

module axil_intc_wr_monitor (
    input logic p_aclk,
    input logic p_bvalid,
    input logic [1:0] p_bresp
);

    // Passive monitor: samples the bundle on posedge p_aclk when p_bvalid
    always @(posedge p_aclk) begin
        if (p_bvalid) begin
            $display("[%0t] axil_intc_wr_monitor: p_bvalid=%0d p_bresp=%0d", $time, p_bvalid, p_bresp);
        end
    end

endmodule

module axil_intc_rd_monitor (
    input logic p_aclk,
    input logic p_rvalid,
    input logic [31:0] p_rdata,
    input logic [1:0] p_rresp
);

    // Passive monitor: samples the bundle on posedge p_aclk when p_rvalid
    always @(posedge p_aclk) begin
        if (p_rvalid) begin
            $display("[%0t] axil_intc_rd_monitor: p_rvalid=%0d p_rdata=%0d p_rresp=%0d", $time, p_rvalid, p_rdata, p_rresp);
        end
    end

endmodule

module axil_intc_axil_checker (
    input logic p_aclk,
    input logic p_areset_n,
    input logic p_awvalid,
    input logic p_bvalid,
    input logic p_arvalid,
    input logic p_rvalid,
    input logic [31:0] p_rdata,
    input logic [1:0] p_rresp
);

    // write_response_arrives: p_bvalid must arrive within 16 cycles of p_awvalid
    logic write_response_arrives_pending;
    logic [31:0] write_response_arrives_wait;
    always @(posedge p_aclk) begin
        if (!p_areset_n) begin
            write_response_arrives_pending <= 1'b0;
            write_response_arrives_wait <= 32'd0;
        end else if (write_response_arrives_pending) begin
            if (p_bvalid) begin
                write_response_arrives_pending <= 1'b0;
            end else if (write_response_arrives_wait >= 32'd16) begin
                $error("CHECK FAIL: write_response_arrives: p_bvalid did not arrive within 16 cycles of p_awvalid");
                write_response_arrives_pending <= 1'b0;
            end else begin
                write_response_arrives_wait <= write_response_arrives_wait + 32'd1;
            end
        end else if (p_awvalid) begin
            write_response_arrives_pending <= 1'b1;
            write_response_arrives_wait <= 32'd0;
        end
    end

    // read_data_arrives: p_rvalid must arrive within 16 cycles of p_arvalid
    logic read_data_arrives_pending;
    logic [31:0] read_data_arrives_wait;
    always @(posedge p_aclk) begin
        if (!p_areset_n) begin
            read_data_arrives_pending <= 1'b0;
            read_data_arrives_wait <= 32'd0;
        end else if (read_data_arrives_pending) begin
            if (p_rvalid) begin
                read_data_arrives_pending <= 1'b0;
            end else if (read_data_arrives_wait >= 32'd16) begin
                $error("CHECK FAIL: read_data_arrives: p_rvalid did not arrive within 16 cycles of p_arvalid");
                read_data_arrives_pending <= 1'b0;
            end else begin
                read_data_arrives_wait <= read_data_arrives_wait + 32'd1;
            end
        end else if (p_arvalid) begin
            read_data_arrives_pending <= 1'b1;
            read_data_arrives_wait <= 32'd0;
        end
    end

    // rdata_holds_between_reads: p_rdata stable one cycle after p_arvalid deasserts
    logic rdata_holds_between_reads_enable_prev;
    logic [31:0] rdata_holds_between_reads_signal_prev;
    always @(posedge p_aclk) begin
        rdata_holds_between_reads_enable_prev <= p_arvalid;
        rdata_holds_between_reads_signal_prev <= p_rdata;
    end
    always @(posedge p_aclk) begin
        if (p_areset_n && !rdata_holds_between_reads_enable_prev && (p_rdata !== rdata_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: rdata_holds_between_reads: p_rdata changed while p_arvalid was deasserted last cycle (was %0d, now %0d)", rdata_holds_between_reads_signal_prev, p_rdata);
        end
    end

    // rresp_holds_between_reads: p_rresp stable one cycle after p_arvalid deasserts
    logic rresp_holds_between_reads_enable_prev;
    logic [1:0] rresp_holds_between_reads_signal_prev;
    always @(posedge p_aclk) begin
        rresp_holds_between_reads_enable_prev <= p_arvalid;
        rresp_holds_between_reads_signal_prev <= p_rresp;
    end
    always @(posedge p_aclk) begin
        if (p_areset_n && !rresp_holds_between_reads_enable_prev && (p_rresp !== rresp_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: rresp_holds_between_reads: p_rresp changed while p_arvalid was deasserted last cycle (was %0d, now %0d)", rresp_holds_between_reads_signal_prev, p_rresp);
        end
    end

endmodule

// Attach the scaffolds. `bind` connects to nets resolved in the DUT's
// own scope, which is why every port above is named after one.
bind axil_intc axil_intc_wr_monitor u_axil_intc_wr_monitor (
    .p_aclk(p_aclk),
    .p_bvalid(p_bvalid),
    .p_bresp(p_bresp)
);

bind axil_intc axil_intc_rd_monitor u_axil_intc_rd_monitor (
    .p_aclk(p_aclk),
    .p_rvalid(p_rvalid),
    .p_rdata(p_rdata),
    .p_rresp(p_rresp)
);

bind axil_intc axil_intc_axil_checker u_axil_intc_axil_checker (
    .p_aclk(p_aclk),
    .p_areset_n(p_areset_n),
    .p_awvalid(p_awvalid),
    .p_bvalid(p_bvalid),
    .p_arvalid(p_arvalid),
    .p_rvalid(p_rvalid),
    .p_rdata(p_rdata),
    .p_rresp(p_rresp)
);
