// Verification scaffolds for sync_fifo, generated by SemiCraft (P4-09).
//
// Simulation only: these modules drive nothing and are attached with
// SystemVerilog `bind`, so adding this file to a compile changes no
// synthesised logic and needs no edit to the design or the testbench.
// Compile it alongside sync_fifo.sv and the checks attach themselves.

module sync_fifo_rd_monitor (
    input logic clk,
    input logic rd_en,
    input logic [7:0] rd_data
);

    // Passive monitor: samples the bundle on posedge clk when rd_en
    always @(posedge clk) begin
        if (rd_en) begin
            $display("[%0t] sync_fifo_rd_monitor: rd_en=%0d rd_data=%0d", $time, rd_en, rd_data);
        end
    end

endmodule

module sync_fifo_rd_checker (
    input logic clk,
    input logic rst,
    input logic rd_en,
    input logic [7:0] rd_data
);

    // read_data_holds_between_reads: rd_data stable one cycle after rd_en deasserts
    logic read_data_holds_between_reads_enable_prev;
    logic [7:0] read_data_holds_between_reads_signal_prev;
    always @(posedge clk) begin
        read_data_holds_between_reads_enable_prev <= rd_en;
        read_data_holds_between_reads_signal_prev <= rd_data;
    end
    always @(posedge clk) begin
        if (!rst && !read_data_holds_between_reads_enable_prev && (rd_data !== read_data_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: read_data_holds_between_reads: rd_data changed while rd_en was deasserted last cycle (was %0d, now %0d)", read_data_holds_between_reads_signal_prev, rd_data);
        end
    end

endmodule

// Attach the scaffolds. `bind` connects to nets resolved in the DUT's
// own scope, which is why every port above is named after one.
bind sync_fifo sync_fifo_rd_monitor u_sync_fifo_rd_monitor (
    .clk(clk),
    .rd_en(rd_en),
    .rd_data(rd_data)
);

bind sync_fifo sync_fifo_rd_checker u_sync_fifo_rd_checker (
    .clk(clk),
    .rst(rst),
    .rd_en(rd_en),
    .rd_data(rd_data)
);
