// Verification scaffolds for sync_fifo, generated by SemiCraft (P4-09).
//
// Simulation only: these modules drive nothing and are attached with
// SystemVerilog `bind`, so adding this file to a compile changes no
// synthesised logic and needs no edit to the design or the testbench.
// Compile it alongside sync_fifo.sv and the checks attach themselves.

module sync_fifo_rd_monitor (
    input logic p_clk,
    input logic p_rdEn,
    input logic [7:0] p_rdData
);

    // Passive monitor: samples the bundle on posedge p_clk when p_rdEn
    always @(posedge p_clk) begin
        if (p_rdEn) begin
            $display("[%0t] sync_fifo_rd_monitor: p_rdEn=%0d p_rdData=%0d", $time, p_rdEn, p_rdData);
        end
    end

endmodule

module sync_fifo_rd_checker (
    input logic p_clk,
    input logic p_rst_n,
    input logic p_rdEn,
    input logic [7:0] p_rdData
);

    // read_data_holds_between_reads: p_rdData stable one cycle after p_rdEn deasserts
    logic read_data_holds_between_reads_enable_prev;
    logic [7:0] read_data_holds_between_reads_signal_prev;
    always @(posedge p_clk) begin
        read_data_holds_between_reads_enable_prev <= p_rdEn;
        read_data_holds_between_reads_signal_prev <= p_rdData;
    end
    always @(posedge p_clk) begin
        if (p_rst_n && !read_data_holds_between_reads_enable_prev && (p_rdData !== read_data_holds_between_reads_signal_prev)) begin
            $error("CHECK FAIL: read_data_holds_between_reads: p_rdData changed while p_rdEn was deasserted last cycle (was %0d, now %0d)", read_data_holds_between_reads_signal_prev, p_rdData);
        end
    end

endmodule

// Attach the scaffolds. `bind` connects to nets resolved in the DUT's
// own scope, which is why every port above is named after one.
bind sync_fifo sync_fifo_rd_monitor u_sync_fifo_rd_monitor (
    .p_clk(p_clk),
    .p_rdEn(p_rdEn),
    .p_rdData(p_rdData)
);

bind sync_fifo sync_fifo_rd_checker u_sync_fifo_rd_checker (
    .p_clk(p_clk),
    .p_rst_n(p_rst_n),
    .p_rdEn(p_rdEn),
    .p_rdData(p_rdData)
);
